name: Tests
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -timeout 30s ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    steps:
      # Creates a release and attaches
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
